# Generated by Django 4.2.3 on 2023-08-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_details',
            fields=[
                ('Book_name', models.CharField(max_length=100)),
                ('Book_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
